# First Aid mod definition file
modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Untrustedlife/FirstAidCrashFix"
displayURL="https://minecraft.curseforge.com/projects/uls-firstaid-fork" 
logoFile="firstaid_logo.png"
authors="Untrustedlife"
license="Main Mod: GPLv3, API: LGPL v2.1"
[[mods]]
    modId="firstaid"
    version="${file.jarVersion}"
    displayName="ULs First Aid Fork"
    description="First Aid is a game changing mod focused around a new health system, this is a fork of that mod that fixes a game brekaing crash and other issues"
    credits="Thanks to Ichttt for making the original mod, and thanks to rozarke for designing the textures for FirstAid!"
[[dependencies.firstaid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firstaid]]
    modId="playerrevive"
    mandatory=false
    versionRange="[2.0.8,)"
    ordering="NONE"
    side="BOTH"